[parity]
chain = "smartNet.json"
db_path = "./data/miner"
keys_path = "./keys"

[dapps]
path = "./dapps"

[network]
reserved_peers = "./network.txt"

[rpc]
disable = false
port = 8545
apis = ["all"]
cors = ["*"]
hosts = ["all"]
interface = "all"

[account]
unlock = ["0xDe554B6c292f5e5794A68Dc560a537DD89d3b03E", "0x9CA9d2D5E04012C9Ed24C0e513C9bfAa4A2dD77f", "0xa5F108b6d82b9F080325F935F3BAf89e0042CAC8"]
password = ["node.pwds"]

[mining]
engine_signer = "0xDe554B6c292f5e5794A68Dc560a537DD89d3b03E"
reseal_on_txs = "none"
min_gas_price = 100

[misc]
logging = "lsync=trace,txqueue=trace,own_tx=trace"

[ipc]
disable = false
apis = ["all"]

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["all"]
hosts = ["all"]

[footprint]
tracing = "auto"
